---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: serving-showcase
spec:
  template:
    spec:
      containers:
        - image: quay.io/cardil/knative-serving-showcase
#          env:
#            - name: DELAY
#              value: 1350
          readinessProbe:
            httpGet:
              path: /health/ready
          livenessProbe:
            httpGet:
              path: /health/live
