---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plain-showcase
  labels:
    app: plain-showcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plain-showcase
  template:
    metadata:
      labels:
        app: plain-showcase
    spec:
      containers:
        - name: plain-showcase
          image: quay.io/cardil/knative-serving-showcase
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 21111
          livenessProbe:
            httpGet:
              path: /health/live
              port: 21111
---
apiVersion: v1
kind: Service
metadata:
  name: plain-showcase
spec:
  selector:
    app: plain-showcase
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 21111
