####
# This Containerfile is used in order to build a container that runs the Quarkus application in JVM mode
#
# Build the app with:
#
# ./mvnw package
#
# Build the image with:
#
# podman build -f src/main/container/jvm/Containerfile -t cardil/knative-serving-showcase:jvm .
#
# Then run the container using:
#
# podman run -i --rm -p 21111:21111 cardil/knative-serving-showcase:jvm
#
###

FROM registry.access.redhat.com/ubi8/openjdk-17

ENV LANGUAGE='en_US:en'


# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
