####
# This Containerfile is used in order to build a container that runs the Quarkus application in JVM mode
#
# Build the image with:
#
# podman build -f src/main/container/jvm-standalone/Containerfile \
#   -t cardil/knative-serving-showcase:jvm .
#
# Then run the container using:
#
# podman run -i --rm -p 21111:21111 cardil/knative-serving-showcase:jvm
#
###

ARG UBI_VERSION=8.7
FROM registry.access.redhat.com/ubi8/openjdk-17 as builder

USER root
RUN useradd --create-home --home-dir /project quarkus
USER quarkus
ADD --chown=quarkus . /project/work
WORKDIR /project/work
ENV MVNW_VERBOSE=true
RUN ./mvnw -V -B --no-transfer-progress -Dmaven.artifact.threads=50 dependency:go-offline
RUN ./mvnw -V -B --no-transfer-progress verify

ARG UBI_VERSION=8.7
FROM registry.access.redhat.com/ubi8/ubi-minimal:${UBI_VERSION}

ARG JAVA_PACKAGE=java-17-openjdk-headless
ARG RUN_JAVA_VERSION=1.3.8

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
# Install java and the run-java script
# Also set up permissions for user `1001`
RUN microdnf install curl ca-certificates ${JAVA_PACKAGE} \
    && microdnf update \
    && microdnf clean all \
    && mkdir /deployments \
    && chown 1001 /deployments \
    && chmod "g+rwX" /deployments \
    && chown 1001:root /deployments \
    && curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh \
    && chown 1001 /deployments/run-java.sh \
    && chmod 540 /deployments/run-java.sh \
    && echo "securerandom.source=file:/dev/urandom" >> /etc/alternatives/jre/lib/security/java.security

# Configure the JAVA_OPTIONS, you can add -XshowSettings:vm to also display the heap size.
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --from=builder --chown=1001 /home/jboss/work/target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder --chown=1001 /home/jboss/work/target/quarkus-app/*.jar /deployments/
COPY --from=builder --chown=1001 /home/jboss/work/target/quarkus-app/app/ /deployments/app/
COPY --from=builder --chown=1001 /home/jboss/work/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 21111
USER 1001

ENTRYPOINT [ "/deployments/run-java.sh" ]
