####
# This Containerfile is used in order to build a container that runs the Quarkus application in JVM mode
#
# Build the image with:
#
# podman build -f src/main/container/jvm-standalone/Containerfile \
#   -t cardil/knative-serving-showcase:jvm .
#
# Then run the container using:
#
# podman run -i --rm -p 21111:21111 cardil/knative-serving-showcase:jvm
#
###

FROM registry.access.redhat.com/ubi8/openjdk-17 as builder

USER root
RUN useradd --create-home --home-dir /project quarkus
USER quarkus
ADD --chown=quarkus . /project/work
WORKDIR /project/work
ENV MVNW_VERBOSE=true
RUN ./mvnw -V -B --no-transfer-progress -Dmaven.artifact.threads=50 dependency:go-offline
RUN ./mvnw -V -B --no-transfer-progress verify

FROM registry.access.redhat.com/ubi8/openjdk-17

ENV LANGUAGE='en_US:en'


# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --from=builder --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --from=builder --chown=185 target/quarkus-app/*.jar /deployments/
COPY --from=builder --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --from=builder --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
