---
name: Container build

on:
  schedule:
    # everyday at 10am
    - cron: '0 10 * * *'
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

env:
  REGISTRY: quay.io
  IMAGE_NAME: cardil/knative-serving-showcase

jobs:
  build-image:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        kind:
          - jvm
          # FIXME: native is not working https://github.com/cardil/knative-serving-showcase/issues/1
          # - native-standalone
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: .github/workflows/prepare.sh ${{ matrix.kind }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Pre-build artifacts
        uses: redhat-actions/buildah-build@v2
        if: ${{ steps.prep.outputs.pre_build == 'true' }}
        with:
          image: builder
          tags: ${{ github.sha }}
          containerfiles: ./src/main/container/${{ matrix.kind }}/build.Containerfile
          platforms: linux/amd64
          extra-args: --ulimit nofile=4096:4096

      - name: Extract build artifacts from OCI image
        if: ${{ steps.prep.outputs.pre_build == 'true' }}
        run: .github/workflows/extract.sh localhost/builder:${{ github.sha }}

      - name: Build the multi-arch image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          containerfiles: ./src/main/container/${{ matrix.kind }}/Containerfile
          tags: ${{ steps.prep.outputs.tags }}
          platforms: ${{ steps.prep.outputs.platforms }}
          extra-args: --ulimit nofile=4096:4096
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.kind=${{ matrix.kind }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

      - name: Login to registry
        uses: redhat-actions/podman-login@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Push to registry
        if: ${{ github.event_name != 'pull_request' }}
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.build-image.outputs.tags }}

      - name: Print image url
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"
